### PR TITLE
Allow snipping to a substring's index + documentation and tests

### PR DESCRIPTION
**Pull request by iabw**
I was hoping you'd be receptive to this pull request to extend this plugin's functionality. The default code path remains the same as previously. Comes with documentation and tests.

In the process of implementing a metalsmith example for https://github.com/remotesynth/Static-Site-Samples, I found that there wasn't a way to make metalsmith-snippet snip to a variable pre-defined point in the contents. When looking at the Wintersmith example from that repo, I ended up finding Wintersmith's source code, which has the following function - https://github.com/jnordberg/wintersmith/blob/a397ae71855df55a9bdfa03eb16f7571b511ca55/src/plugins/page.coffee#L114

It seems like it should be part of this plugin, although I'll make it its own "metalsmith-intro" plugin if you don't agree.

### CODE REVIEW

**Comment by blakeembrey** [comment]
Awesome! There's a couple of tweaks that we should look at, but this is great :+1: For the options, what about having `maxLength` and `breaks`? They can be used in tandem, or by removing one or the other.

**Comment by iabw** [comment]
Yeah, I don't care what the names of the new options are. I also felt that maybe you should be able to define the breaks right on the `stopAtSubstring` parameter, instead of needing to have both. How do you feel about `stopAtSubstring`? If we're calling it breaks, maybe that should just be `useBreaks`?

Just to confirm - by using both in tandem you mean that the files get to do either. So if they have one of the `breaks`, that gets used, and if they don't it would use `maxLength`.

**Comment by blakeembrey** [comment]
Sorry, I meant that existence of the option would indicate usage. So, valid options are:

``` js
// Just stop at 300 characters.
maxLength: 300
```

Or the new option:

``` js
// Only stop on the break.
breaks: ['<h2']
```

Or, maybe, for some reason, do both!

``` js
// Stops on the break, or at 300 characters (whichever comes first).
maxLength: 300,
breaks: ['<h2']
```

I'm just proposing that we don't limit it to one option or the other, but support both and use existence as the definition. It also makes `break` be around a 4 line addition to the code.

**Comment by iabw** [comment]
So it would still default to `maxLength`, `breaks` would not have a default value, and `stopAtSubstring` goes away completely, correct?

I'm fine with that. Wintersmith's defaults seemed a little arbitrary to me anyway.

**Comment by iabw** [comment]
I DO think it would be better to leave the 2 index checks ( `maxLength` vs looping over the `breaks` ) as separate, because of how the `maxLength` trashes html tags, since existing html tags is specifically the use case trying to be solved ( ie - migrating from Wintersmith without changing all the content files ).

And if the checks are separate, their substr methods sort of have to be too ( since one would have html entities and one won't ).

**Comment by blakeembrey** [comment]
Wait, when would you want HTML entities with the snippet? If that's the case, maybe a different module is a good idea.

**Comment by iabw** [comment]
I don't want to belabor the discussion, but...

Since my original intention was to help smooth the transition from Wintersmith -> Metalsmith in that Adventure Time example site, I figured html entities should be left alone, since Wintersmith's `getIntro` method specifically looks for them. 

I'm also not sure how you'd have a break to look for that wasn't displayed like real text in the file contents, since html entities get cleaned out. You stop being able to have a generic "Read More" type break like Wintersmith does with `<span class="more">`.

That said, a separate module would be fine by me. Especially if we cross-linked the modules so that someone who finds metalsmith-snippet but wants metalsmith-intro ( or vice versa ), wouldn't be left in the dark. Then metalsmith-intro can have an option to clear html entities or not after it's parsed out the intro - because I agree with you that the actual snippet would usually be expected to be plain text.

Thanks for talking through this and with such responsiveness, btw! Hugely appreciated.

**Comment by blakeembrey** [comment]
It's easy enough to break on the HTML tags and still strip the contents according to `maxLength`. I'll make the changes to support that still. Rethinking it though, I'll make the change on top of yours to support this and then we should make another change to not strip HTML.

The thing with splitting on HTML is that you're going to generate invalid HTML. So for that you need to make sure you re-close the HTML entities. Which means it's going to get tricky and you'll be making either a psuedo HTML parser or we should use one that already exists. Does that make sense?

Sorry, I'm pretty tired from yesterday so I might not be thinking thoroughly, but now I actually think that we just need an option to maintain HTML. Maybe `html: true`?

**Comment by iabw** [comment]
That's a really good point about needing to close any currently open html tags. I hadn't considered it because I don't think Wintersmith does.

If you're willing to have potentially buggier but simpler code for identical functionality to Wintersmith, I would say don't parse and just have a note to not use that functionality after turning markdown into html.

OR - you could just clean out the html tags after it's snipped when using `breaks` and not support html tags in the snippet at all. I'm fine with that, personally.

**Comment by blakeembrey** [comment]
Great, I think I'll do both. Let me fix this and review it tomorrow now. I'll release a `2.0` with `maxLength`, `stops` and `html` options based on your PR.

**Comment by blakeembrey** [comment]
@iabw Took me a few hours, but I got a basic "HTML parser" running and rewrote everything for `v2.0`.

https://github.com/blakeembrey/metalsmith-snippet/releases/tag/v2.0.0

Let me know if it solves your problems :+1: It just means the stop is configurable always.

**Comment by iabw** [comment]
Thanks Blake! I really wasn't trying to create work for you, but this is great.

**Comment by blakeembrey** [comment]
No worries, it was fun :smile:

**Pull request merged**
